### ISSUE TITLE
Membership View Accounts -> Options -> account button

### ISSUE THREAD

**Issue by vpsantow** [wingblaze/ggms#10]
After selecting "account button" in the page. I get an error

`FatalErrorException in b6982cffd675db81396b86b89a2dd55ecdfdbc34.php line 39:
Call to undefined function prettify_text()`

![image](https://cloud.githubusercontent.com/assets/17693687/13905258/c99cf6c2-eef5-11e5-963c-3b297129899b.png)

After further testing complaints to pending accounts also lead to this error

**Comment by wingblaze** [comment]
Please pull the code and do the following

`composer dump-autoload`

Reference [How to create Helpers file in Laravel 5](http://www.techigniter.in/tutorials/how-to-create-helpers-file-in-laravel-5/).
