### ISSUE TITLE
Facilities Checkboxes

### ISSUE THREAD

**Issue by vpsantow** [wingblaze/ggms#4]
Agreed upon checkboxes are:
- Projector
- Chairs
- Tables
- Dining Setup
- In-house Catering

Add a text field as well for contact person's no. (if it was by a non-member) -Paolo

**Comment by wingblaze** [comment]
Implemented this dynamically. This can now easily change depending on the requirements (e.g. You plan to change this in the future into a more diverse checklist).

---

**Checklist on the event creation form**

![image](https://cloud.githubusercontent.com/assets/8447886/13868760/4c944a4e-ed07-11e5-93ea-10ea08bf0164.png)

---

**Viewing preparation details of an event**
This is only viewable by marketing manager.

![image](https://cloud.githubusercontent.com/assets/8447886/13868750/2eebb14e-ed07-11e5-8c50-6c982f1d13a2.png)

---

Representation in the database is JSON.

![image](https://cloud.githubusercontent.com/assets/8447886/13868746/1e83cb52-ed07-11e5-9ac7-304ceeebbfa2.png)
