### ISSUE TITLE
Groups Page

### ISSUE THREAD

**Issue by vpsantow** [wingblaze/ggms#6]
Pls do add a "Industry Tab/Detail" to classify every entry in the groups page. The classifications are as follows:
1.  Section A – Agriculture, forestry and fishing
2. \- Section B – Mining and Quarrying
3. \- Section C – Manufacturing
4. \- Section D – Electricity, gas, steam and air-conditioning supply
5. \- Section E – Water supply, sewerage, waste management and remediation activities
6. \- Section F – Construction
7. \- Section G – Wholesale and retail trade; repair of motor vehicles and motorcycles
8. \- Section H – Transportation and Storage
9. \- Section I – Accommodation and food service activities
10. \- Section J – Information and Communication
11. \- Section K – Financial and insurance activities
12. \- Section L – Real estate activities
13. \- Section M – Professional, scientific and technical services
14. \- Section N – Administrative and support service activities
15. \- Section O – Public administrative and defense; compulsory social security
16. \- Section P – Education
17. \- Section Q – Human health and social work activities
18. \- Section R – Arts, entertainment and recreation
19. \- Section S – Other service activities
20. \- Section T – Activities of private households as employers and undifferentiated goods and services and producing activities of households for own use
21. \- Section U – Activities of extraterritorial organizations and bodies

**Comment by wingblaze** [comment]
![image](https://cloud.githubusercontent.com/assets/8447886/13868021/dab769e4-ecff-11e5-969e-69debf5d8344.png)

In group creation form, changed input field `type` from _input text field_ into _dropdown menu_ with the abovementioned options.

**Comment by wingblaze** [comment]
![image](https://cloud.githubusercontent.com/assets/8447886/13867984/90fa0366-ecff-11e5-8d72-6230ffebdb80.png)

Groups are now displayed by categories. Assign someone to populate the groups entries in the `GroupTableSeeder` file. See the file for the template, or see below.

```
DB::table('groups')->insert([
            'name' => 'De La Salle College of Saint Benilde',
            'description' => "Amazing HRIM and Multimedia arts students.",
            'type' => "Education",
            'address' => '2402 Taft Avenue',
            'phone' => '63-2-323-4347',
            'fax' => '63-2-924-1242'
            ]);
```
